<?php
$z[0]=Array("global","",145,166);
$z[0][4]['name']="cfg_dh";
$z[1]=Array("global","",285,306);
$z[1][4]['name']="cfg_qq";
$z[2]=Array("channel"," <a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a> ",1659,1783);
$z[2][4]['type']="top";
$z[2][4]['row']="8";
$z[3]=Array("flink","[field:link /]",1887,1935);
$z[3][4]['row']="50";
$z[4]=Array("global","",2049,2070);
$z[4][4]['name']="cfg_dh";
$z[5]=Array("global","",2103,2124);
$z[5][4]['name']="cfg_yx";
$z[6]=Array("global","",2157,2178);
$z[6][4]['name']="cfg_dz";
$z[7]=Array("global","",2194,2220);
$z[7][4]['name']="cfg_powerby";
$z[8]=Array("global","",2398,2422);
$z[8][4]['name']="cfg_beian";

?>