<?php
$z[0]=Array("global","",116,142);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",259,280);
$z[1][4]['name']="cfg_dh";
$z[2]=Array("channel","\r\n        <li> <a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a> </li>\r\n        ",477,630);
$z[2][4]['type']="top";
$z[2][4]['row']="8";
$z[3]=Array("arclist","\r\n      <li><a><img src=\"[field:litpic/]\" /></a></li>\r\n      ",761,885);
$z[3][4]['row']="5";
$z[3][4]['titlelen']="36";
$z[3][4]['typeid']="14";
$z[4]=Array("global","",1310,1335);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("arclist","\r\n            <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><span>[field:title/]</span>\r\n              <label> [field:pubdate function='strftime(\"%Y-%m-%d\",@me)'/]</label>\r\n              </a></li>\r\n            ",1950,2229);
$z[5][4]['row']="5";
$z[5][4]['titlelen']="52";
$z[5][4]['typeid']="8";

?>